apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kwjillc38-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/kwjillc38-java-springboot-gitops